### ISSUE TITLE
运行 python conda 环境问题

### ISSUE THREAD

**Issue by decajoin** [Kicamon/running.nvim#1]
你好👋，我在使用的时候遇到了一点问题，就是我在启动 nvim 之前已经使用 conda 切换了环境，但是在使用插件运行时还是使用的 base 环境，导致代码无法正常运行，请问这个有什么解决方法吗。期待你的解答，感谢！

**Comment by Kicamon** [comment]
啊，我不写python，不是很懂它的环境。我配置的默认的python的运行命令是python3 文件名，不知道是不是这个问题，如果是的话可以在配置里改一下

**Comment by decajoin** [comment]
好滴，我研究一下，感谢啦！
